name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      DATABASE_NAME: allianceauth
      DATABASE_USER: allianceauth
      DATABASE_PASSWORD: allianceauth

    runs-on: ubuntu-latest

    services:

      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_USER: ${{ env.DATABASE_USER }}
          MYSQL_PASSWORD: ${{ env.DATABASE_PASSWORD }}
          MYSQL_DATABASE: ${{ env.DATABASE_NAME }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
        options: >-
          --health-cmd="/usr/local/bin/healthcheck.sh --connect" 
          --health-interval=10s 
          --health-timeout=3s 
          --health-retries=3

      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: '**/requirements.txt'

    - run: pip install -r requirements.txt

    - name: Run Tests
      env:
        DJANGO_DEBUG: True
        DJANGO_SECRET_KEY: secret
        SECRET_KEY: secret
        REDIS_HOST: 127.0.0.1
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_NAME: ${{ env.DATABASE_NAME }}
        DB_USER: ${{ env.MYSQL_ROOT_USER }}
        DB_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
        ESI_CLIENT_ID: fakeclientid
        ESI_SECRET_KEY: fakesecretkey
        ESI_USER_CONTACT_EMAIL: webmaster@site.local
        SITE_URL: http://localhost:8000
        EMAIL_HOST: mailcatcher
        EMAIL_PORT: 1025
        EMAIL_USE_TLS: False
        DEFAULT_FROM_EMAIL: webmaster@site.local
      run: pytest
